account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

import account
from . import views


app_name = "account"

urlpatterns = [

]

accountapp/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from accountapp.views import hello_world, AccountCreateView, AccountDetailView, AccountUpdateView, AccountDeleteView

app_name = "accountapp"

urlpatterns = [
    path('hello_world/', hello_world, name='hello_world'), #함수형\
    path('login/', LoginView.as_view(template_name='accountapp/login.html'), name="login"),
    path('logout/', LogoutView.as_view(), name="logout"),

    path('create/', AccountCreateView.as_view(), name="create"),
    path('detail/<int:pk>', AccountDetailView.as_view(), name="detail"),
    path('update/<int:pk>', AccountUpdateView.as_view(), name="update"),
    path('delete/<int:pk>', AccountDeleteView.as_view(), name="delete")

]

common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "common"

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

pragmatic/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('account/', include('account.urls')),
    path('common/', include('common.urls'))

]

accountapp/models.py
from django.db import models

# Create your models here.

class HelloWorld(models.Model):
    text = models.CharField(max_length=255, null=False)

common/models.py
from django.db import models

# Create your models here.

accountapp/forms.py
from django.contrib.auth.forms import UserCreationForm


class AccountUpdateForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['username'].disabled = True

account/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.db import connection
import datetime

# Create your views here.
from django.urls import reverse


def t_login(request):
    if request.method == 'POST':

        return render(request, 't_home.html')
    else:

        return render(request, 't_login.html')


def t_sign_up(request):

    if request.method == 'POST':

        user_id = request.POST['user']
        password = request.POST['password']
        user_name = request.POST['user_name']
        user_email = request.POST['user_email']
        user_tel = request.POST['user_tel']
        now = datetime.datetime.now()

        cursor = connection.cursor()
        sql = "insert into m_user (user, password, user_name, user_email, user_tel, user_typ, regi_typ, permit_yn, regi_dt) value (%s, %s, %s, %s, %s, %s, %s, %s, %s)"
        cursor.execute(sql, (user_id, password, user_name, user_email, user_tel, 'U', 'H', 'Y', now))
        cursor.close()

        return render(request, 't_login.html', context={'result':'success'})

    else:
        return render(request, 't_sign_up.html')

accountapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView

from accountapp.forms import AccountUpdateForm
from accountapp.models import HelloWorld

@login_required
def hello_world(request):

    # if request.user.is_authenticated: #로그인 되어있는경우

        if request.method == "POST":

            temp = request.POST.get('hello_world_input')

            new_hello_world = HelloWorld()
            new_hello_world.text = temp
            new_hello_world.save()

            hello_world_list = HelloWorld.objects.all()
            return HttpResponseRedirect(reverse('accountapp:hello_world'))

        else:

            hello_world_list = HelloWorld.objects.all()
            return render(request, 'accountapp/helloworld.html', context={'hello_world_list': hello_world_list})

    # else: #로그인이 안되어 있는 경우
    #     return HttpResponseRedirect(reverse('accountapp:login'))


class AccountCreateView(CreateView):
    model = User
    form_class = UserCreationForm
    success_url = reverse_lazy('accountapp:hello_world') #성공 후 어느경로로 재 연결?
    # reverse / reverse_lazy
    # reverse는 클래스에서 사용할 수 없음
    template_name = 'accountapp/create.html' #회원가입시 보여줄 form 어느 html 파일을 통해 보여줄지


class AccountDetailView(DetailView):
    model = User
    context_object_name = 'target_user'
    template_name = 'accountapp/detail.html'


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
# 일반 function에 사용하는 decorator를 method에 사용하도록 하는 decorator
class AccountUpdateView(UpdateView):
    model = User
    form_class = AccountUpdateForm
    context_object_name = 'target_user'
    success_url = reverse_lazy('accountapp:hello_world')
    template_name = 'accountapp/update.html'


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class AccountDeleteView(DeleteView):
    model = User
    context_object_name = 'target_user'

    success_url = reverse_lazy('accountapp:login')
    template_name = 'accountapp/delete.html'

common/views.py
from django.shortcuts import render

# Create your views here.

account/templates/form_errors.html
<!-- ------------------------------- [edit] -------------------------------- -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- ----------------------------------------------------------------------- -->

account/templates/t_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    가입성공
</body>
</html>

account/templates/t_login.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Please, Sure</title>
	<link rel="icon" href="/images/logo/favi.png">
<!--	<link rel="stylesheet" href="/css/reset.css" type="text/css"/>-->
<!--	<link href="/css/header.css" rel="stylesheet">-->
	<link rel="stylesheet" href="{% static 'css/style.css'%}" type="text/css"/>
<!--	<link rel="stylesheet" href="/css/style.css" type="text/css"/>-->
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;400;500;700&display=swap" rel="stylesheet">
</head>

<body>
{{ result }}
	<div id="wrap">
		<div id="container">
			<section id="content" class="login_box">
				<div class="logo_area">
					<img src="/images/logo/logo2.png" alt="로고이미지" >
				</div>
				<form name="login" action="" method="post">
					{% csrf_token %}
					<div class="input_wrap">
						<div class="input_boxx mg_bottom_10">
							<input type="text" id="user" name="user" placeholder="아이디 입력" >
                            <!-- <p class="comm red"> @if($errors->get('user')) 아이디를 입력해 주세요. @endif</p> -->
                        </div>

						<div class="input_boxx">
							<input type="password" id="password" name="password" placeholder="비밀번호 입력"autocomplete="off">
                            <!-- <p class="comm red"> @if($errors->get('password')) 비밀번호를 입력해 주세요. @endif</p> -->
						</div>

					</div><!-- input_wrap -->
					<div class="input_boxx">

						<span class="comm red">아이디 혹은 비밀번호를 확인해 주세요. </span>
					</div>
					<button id="login" class="btn_1">로그인</button>
                    <div>
                        <a href="{% url 'account:t_sign_up'%}"><button type="button" class="btn_4_shrt f-left">사용자 회원가입</button></a>
                    </div>
					<div class='reset_password'><a href="/auth/password_reset">비밀번호 찾기</a></div>
				</form>

			</section>

		</div>
	</div>

	<script type="text/javascript" src="../js/jquery.js"> </script>
    <script type="text/javascript" src="../js/jquery-ui.min.js"> </script>
</body>
</html>

<script type="text/javascript">


</script>

account/templates/t_sign_up.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">

	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Please, Sure</title>
</head>
<body>

	<div class="wrap">
		<div class="bg_con"></div>
		<div id="container">
		<section id="contents" class="">
			<div class="contents_inner admin_3_inner cf">
                <form id="usr_join_form" name="usr_join_form" action="{% url 'account:t_sign_up' %}" method="post">
					{% csrf_token %}
                <h2 class="mg_left_30">사용자 회원 가입</h2>
					<div class="ad_con_box shadow_1 cf">
						<div class="fll">
						<table class="table_2">
							<caption class="hide">메뉴추가</caption>
							<colgroup>
                                <col width ="10%">
								<col width ="40%">
								<col width ="20%">
								<col width ="30%">
							</colgroup>
							<tbody>
								<tr>
									<th>아이디<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box  inline-block">
											<input type="text" name="user" id="user" placeholder="영문/숫자 4자 이상">
										</div>
                                        &nbsp;
                                        <div class="check  inline-block"><a onclick="user_check();">중복체크</a></div>
                                        <input id="user_chk" name="user_chk" value="" type="text" style="display:none">
                                    </td>

                                    <th>이름</th>
                                    <td>
                                        <div class="input_box">
											<input type="text" name="user_name" id="user_name" placeholder="50글자 이내">
										</div>
                                    <td>
                                </tr>
                                <tr>
									<th>비밀번호<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="password" name="password" id="password" placeholder="영문/숫자 4자이상">
										</div>
                                    </td>
                                    <th>비밀번호확인<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="password" name="password2" id="password2" placeholder="영문/숫자 4자이상">
										</div>
									</td>
                                </tr>

                                <tr>
									<th>이메일<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="text" name="user_email" id="user_email"  class="w200">
										</div>
									</td>
                                    <th>연락처<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="text" name="user_tel" id="user_tel" class="w200" placeholer="010123456789" onkeyup="inputPhoneNumber(this);"/>
										</div>
									</td>
                                </tr>
							</tbody>
						</table>
					</div>
				</div>
                        <button type="submit" >가입하기</button>
                </form>

			</div><!-- contents_inner -->
		</section>

		</div>
	</div>

</body>
</html>

account/templates/test.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">

	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Please, Sure</title>
</head>
<body>
	<div class="wrap">
		<div class="bg_con"></div>
		<div id="container">
		<section id="contents" class="">
			<div class="contents_inner admin_3_inner cf">
                <form id="usr_join_form" name="usr_join_form" action="{% url 'account:t_sign_up' %}" method="post">
					{% csrf_token %}
                <h2 class="mg_left_30">사용자 회원 가입</h2>
					<div class="ad_con_box shadow_1 cf">
						<div class="fll">
						<table class="table_2">
							<caption class="hide">메뉴추가</caption>
							<colgroup>
                                <col width ="10%">
								<col width ="40%">
								<col width ="20%">
								<col width ="30%">
							</colgroup>
							<tbody>
								<tr>
									<th>아이디<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box  inline-block">
											<input type="text" name="user" id="user" placeholder="영문/숫자 4자 이상">
										</div>
                                        &nbsp;
                                        <div class="check  inline-block"><a onclick="user_check();">중복체크</a></div>
                                        <input id="user_chk" name="user_chk" value="" type="text" style="display:none">
                                    </td>

                                    <th>이름</th>
                                    <td>
                                        <div class="input_box">
											<input type="text" name="user_name" id="user_name" placeholder="50글자 이내">
										</div>
                                    <td>
                                </tr>
                                <tr>
									<th>비밀번호<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="password" name="password" id="password" placeholder="영문/숫자 4자이상">
										</div>
                                    </td>
                                    <th>비밀번호확인<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="password" name="password2" id="password2" placeholder="영문/숫자 4자이상">
										</div>
									</td>
                                </tr>

                                <tr>
									<th>이메일<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="text" name="user_email" id="user_email"  class="w200">
										</div>
									</td>
                                    <th>연락처<span class="red">&nbsp; *</span></th>
									<td>
										<div class="input_box">
											<input type="text" name="user_tel" id="user_tel" class="w200" placeholer="010123456789" onkeyup="inputPhoneNumber(this);"/>
										</div>
									</td>
                                </tr>
							</tbody>
						</table>
					</div>
				</div>
                        <button type="submit" >가입하기</button>
                </form>

			</div><!-- contents_inner -->
		</section>

		</div>
	</div>

</body>
</html>

accountapp/templates/accountapp/create.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align:center">
    <form action="{% url 'accountapp:create' %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" class="btn btn-primary">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/delete.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align:center">
    <div class=""mb-4>
      <h4>Quit</h4>
    </div>
    <form action="{% url 'accountapp:delete' pk=target_user.pk %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" class="btn btn-primary">
    </form>
  </div>

{% endblock %}

accountapp/templates/accountapp/detail.html
{% extends 'base.html' %}

{% block content %}
  <div>
    <div style="text-align: center; max-width : 500px; margin: 4rem auto;">
      <p>
        {{ target_user.date_joined }}
      </p>
      <h2>
        {{ user.username }}
      </h2>

      {% if target_user == user%}
<!--      타켓 유저가 지금 접속한 유저랑 같다면-->
      <a href="{% url 'accountapp:update' pk=user.pk %}">
        <p>
          Change Info
        </p>
      </a>
      <a href="{% url 'accountapp:delete' pk=user.pk %}">
        <p>
          Quit
        </p>
      </a>
      {% endif %}
    </div>
  </div>
{% endblock %}

accountapp/templates/accountapp/helloworld.html
{% extends 'base.html' %}

{% block content %}

    <div style="height:20rem; background-color:#38df81; border-radius: 1rem; margin:2rem">
        <h1 >
            HELLO WORLD LIST!
        </h1>
        <form action="/account/hello_world/" method="post">
            {% csrf_token %}
            <div>
                <input type="text" name="hello_world_input">
            </div>
            <div>
                <input type="submit" class="btn btn-primary" value="POST">
            </div>
        </form>
        {% if hello_world_list %}
            {% for hello_world in hello_world_list %}
            <h4>
                {{ hello_world.text }}
            </h4>
        {% endfor %}
        {% endif %}
    </div>

{% endblock %}

accountapp/templates/accountapp/login.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align:center">
      <div>
        <h4>Login</h4>
        <form action="" method="post">
          {% csrf_token %}
          {{ form }}
          <input type="submit" class="btn btn-primary">
        </form>
      </div>
    </div>

{% endblock %}

accountapp/templates/accountapp/update.html
{% extends 'base.html' %}

{% block content %}

  <div style="text-align:center">
    <div class=""mb-4>
      <h4>Change Info</h4>
    </div>
    <form action="{% url 'accountapp:update' pk=user.pk %}" method="post">
      {% csrf_token %}
      {{ form }}
      <input type="submit" class="btn btn-primary">
    </form>
  </div>

{% endblock %}

common/templates/common/form_errors.html
<!-- ------------------------------- [edit] -------------------------------- -->
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}
<!-- ----------------------------------------------------------------------- -->

common/templates/common/login.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<title>Please, Sure</title>
	<link rel="icon" href="/images/logo/favi.png">
<!--	<link rel="stylesheet" href="/css/reset.css" type="text/css"/>-->
<!--	<link href="/css/header.css" rel="stylesheet">-->
	<link rel="stylesheet" href="{% static 'css/style.css'%}" type="text/css"/>
<!--	<link rel="stylesheet" href="/css/style.css" type="text/css"/>-->
	<link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;400;500;700&display=swap" rel="stylesheet">
</head>

<body>
{{ result }}
	<div id="wrap">
		<div id="container">
			<section id="content" class="login_box">
				<div class="logo_area">
로그인페이지	11
                </div>
				<form name="login" action="{% url 'common:login' %}" method="post">
					{% csrf_token %}
					{% include "form_errors.html" %}
					<div class="input_wrap">
						<div class="input_boxx mg_bottom_10">
							<input type="text" id="username" name="username" placeholder="아이디 입력" value="{{ form.username.value|default_if_none:'' }}" >
                        </div>

						<div class="input_boxx">
							<input type="password" id="password" name="password" placeholder="비밀번호 입력"autocomplete="off" value="{{ form.password.value|default_if_none:'' }}">
						</div>

					</div><!-- input_wrap -->
					<div class="input_boxx">

						<span class="comm red">아이디 혹은 비밀번호를 확인해 주세요. </span>
					</div>
					<button id="login" class="btn_1">로그인</button>

				</form>
					<div class='reset_password'><a href="/auth/password_reset">비밀번호 찾기</a></div>
			</section>

		</div>
	</div>

	<script type="text/javascript" src="../js/jquery.js"> </script>
    <script type="text/javascript" src="../js/jquery-ui.min.js"> </script>
</body>
</html>

<script type="text/javascript">


</script>

templates/base.html
<!DOCTYPE html>
<html lang="ko">

    {% include 'head.html' %}

    <body>

    {% include 'header.html' %}

    <hr>
    {% block content %}
    {% endblock %}


    <hr>
    {% include 'footer.html' %}
</body>

</html>

templates/footer.html
<div style="text-align:center; margin-top:2rem;">
    <div style="font-size:.6rem;">
        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스소개</span>
    </div>
    <div style="margin-top: 1rem">
        <h6 class="pragmatic_footer_logo">Pragmatic</h6>
    </div>
</div>

templates/head.html
{% load static %}

<head>

    <meta charset="UTF-8">
    <title>Pragmatic</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <!-- google font link -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- default css link-->
    <link rel="stylesheet" type="text/css" href="{% static 'static/base.css' %}">

</head>

templates/header.html
    <div style="text-align:center; margin:2rem 0; ">
        <div><h1 style="font-family: 'Lobster', cursive;">Pragmatic</h1></div>

            <a href="{% url 'common:login' %}"><span>real_login</span></a>

        <div>
            <span>nav1</span>
            <span>nav2</span>
            <span>nav3</span>
            {% if not user.is_authenticated %}
            <a href="{% url 'accountapp:login' %}?next={{ request.path }}">
                <span>login</span>
            </a>
            <a href="{% url 'accountapp:create' %}">
                <span>Signup</span>
            </a>
            {% else %}
            <a href="{% url 'accountapp:detail' pk=user.pk %}">
                <span>MyPage</span>
            </a>
            <a href="{% url 'accountapp:logout' %}?next={{ request.path }}">
                <span>logout</span>
            </a>
            {% endif %}
        </div>
    </div>

<!--<div style="height:10rem; background-color:#38df81; border-radius: 1rem; margin:2rem">-->

<!--</div>-->